language: php
sudo: false

cache:
  - composer

services:
  - redis-server

mysql:
  database: $APP_DB_NAME
  username: $APP_DB_USER
  encoding: utf8

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

before_script:
  - phpenv config-add tests/travis-php.ini
  - mysql -e 'create database if not exists app_ci3skltn'
  - npm install -q

script:
  - ./vendor/bin/robo php:test

after_script:
  - mysql -e 'drop database if exists app_ci3skltn'

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
